# Generated by Django 5.0.6 on 2024-06-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroAnimal',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_animal', models.CharField(max_length=100)),
                ('especie_animal', models.CharField(max_length=100)),
                ('descripcion_animal', models.TextField()),
                ('anno_nacimiento', models.IntegerField()),
                ('nativo', models.BooleanField(default=False)),
                ('llegada', models.DateField()),
                ('imagen_animal', models.ImageField(null=True, upload_to='fotos/')),
                ('genero_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.generoanimal')),
            ],
        ),
    ]
